config/routes.rb
Rails.application.routes.draw do
  #get 'pages/about'
  #get 'pages/contact'
  #get 'pages/resources'
  devise_for :admin_users, ActiveAdmin::Devise.config


 
  get 'categories/index'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/show'
  get 'home/index'
  root :to=> 'home#index'
  resources :posts
  resources :categories
  ActiveAdmin.routes(self)
  match '/about', :to => 'pages#about', :via => [:get]
  match '/contact', :to => 'pages#contact', :via => [:get]
  match '/resources', :to => 'pages#resources', :via => [:get]
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :all_categories
	helper_method :all_posts

	def all_categories
		@categories = Category.all
	end

	def all_posts
		@posts = Post.all
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @posts = @category.posts

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
		@categorys = Category.all
	
	end

	def create
		@post =  Post.create(post_params)
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved"
		else
			render "new"
		end
	
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(post_params)
			redirect_to post_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
	end

	def show
		@post = Post.find(params[:id])
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"	
	end

	 private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

   def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>
<ul>
  <% @categories.each do|category| %>
   <li> <%= link_to category.name, category %> </li>
   <% end %>
</ul>

app/views/categories/show.html.erb
<% if @posts.each do |post| %>
	<div class="post">
	<h2 class="title"><%= link_to post.title,post %></h2>
	<div class="entry"><%= post.body %></div>
		<div class="byline">
			<p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
			<p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
		</div>
	</div>
	<% end.empty? %>
		<p style="color:#ffffff;">Sorry, there are no posts in this category</p>
<% end %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<h2 class="title"><%= link_to post.title,post %></h2>
		<div class="entry"><%= post.body %></div>
			<div class="byline">
				<p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
				<p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
			</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
  <div id="page">
    <div id="page-bgtop">
      <div id="page-bgbtm">
        <div id="content">
          <div class="flash-message">
            <% flash.each do |key, value| %>
            <p><%= value %></p>
            <% end %>
          </div>
            <%= yield %>
          <div style="clear: both;">&nbsp;</div>
        </div>
        <!-- end #content -->        
        <%= render "partials/sidebar" %>
        <div style="clear: both;">&nbsp;</div>
      </div>
    </div>
  </div>
  
  <!-- end #page -->
  <div id="footer">
    <p>&copy; 2013, My Ruby Blog - Sample Project</p>
  </div>
</div>
<!-- end #footer -->
  </body>
</html>

app/views/pages/about.html.erb
<div class="post">
	<h1>Pages#about</h1>
	<p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
	<h1>Pages#contact</h1>
	<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
	<h1>Pages#resources</h1>
	<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrorblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <div id="header-wrapper">
        <div id="header">
          <div id="logo">
            <h1><a href="#">My Ruby Blog</a></h1>
            <p>Learning Ruby on Rails</p>
          </div>
          <div id="menu">
            <ul class="main-nav">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Blog", posts_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Resources", resources_path %></li>
            </ul>
          </div>
        </div>
      </div>
  <!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
          <ul>
            <li>
              <div id="search" >
                <form method="get" action="#">
                  <div>
                    <input type="text" name="s" id="search-text" value="" />
                    <input type="submit" id="search-submit" value="GO" />
                  </div>
                </form>
              </div>
              <div style="clear: both;">&nbsp;</div>
            </li>
            <li>
              <h2>Get The Framework</h2>
              <p>You can download Ruby and/or Ruby on Rails for free right now
                  <br />
                <a style="color:#D93544;" href="http://rubyonrails.org/download" target="blank">GET IT NOW</a>
              </p>
            </li>
            <li>
              <h2>Categories</h2>
              <ul>
                <% all_categories.each do |cat| %>
                  <li><%= link_to cat.name,category_path(:id => cat.id) %></li>
                <% end %>
              </ul>
            </li>
            <li>
              <h2>Blogroll</h2>
              <ul>
                <% all_posts.each do |post| %>
                  <li><%= link_to post.title,post_path(:id => post.id) %></li>
                <% end %>
              </ul>
            </li>            
          </ul>
        </div>
        <!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
	<div class="entry"><%= post.body %></div>
	<div class="byline">
		<p class="meta">May 07, 2012 Posted by <a href="#">Someone</a></p>
		<p class="links"><a href="post.html">Read More</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="#" title="b0x w">Comments</a></p>
	</div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="post">

	<h1>Show Post</h1>
	<h2><%= @post.title %></h2>
	<small><%= @post.created_at.strftime("%b %d, %y")%></small>
	<p><%= @post.body%></p>
	<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>
	<p><%= link_to "Back", posts_path %></p>

</div>